X = float(input("Напишите Первое Число"))
Y = float(input("Напишите Второе Число"))
print(X + Y)
print(X - Y)
print(X * Y)
print(X / Y)
print("1 Это Сложение 2 Это вычитание 3 Это умножение 4 Деление")
print("Спасибо что использовали калькулятор компании Nico INC! Оставьте отзыв на почте robertmyha303@inbox.ru")
input ()
